name: workup

services:
  app:
    build: .
    image: workup
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      CI_ENV: development

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workup
      MYSQL_USER: workup
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - dados_mysql:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

volumes:
  dados_mysql:
